name: Prueba-Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Listar archivos
        run: ls -la

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar app
        run: npm run dev
